name: Run Pylint and Push Changes

on:
  push:
    branches:
      - main

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust this line based on your project's dependencies

    - name: Run Pylint
      run: |
        pylint your_project_directory  # Replace "your_project_directory" with the actual directory containing your Python code

    - name: Commit and push changes
      run: |
        git config --global user.email "your_email@example.com"
        git config --global user.name "Your Name"
        git add .
        git commit -m "Run Pylint and format code"
        git push origin main
